### ISSUE TITLE
Headless mode error

### ISSUE THREAD

**Issue by Excludos** [mdoube/BoneJ#58]
Attempting to run a BoneJ command in headless mode gives off this error:

```java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.doube.util.ImageCheck.checkEnvironment(ImageCheck.java:240)
        at org.doube.bonej.MeasureSurface.run(MeasureSurface.java:60)
        at ij.IJ.runUserPlugIn(IJ.java:228)
        at ij.IJ.runPlugIn(IJ.java:192)
        at ij.Executer.runCommand(Executer.java:137)
        at ij.Executer.run(Executer.java:66)
        at ij.IJ.run(IJ.java:308)
        at ij.macro.Functions.doRun(Functions.java:613)
        at ij.macro.Functions.doFunction(Functions.java:96)
        at ij.macro.Interpreter.doStatement(Interpreter.java:250)
        at ij.macro.Interpreter.doStatements(Interpreter.java:236)
        at ij.macro.Interpreter.run(Interpreter.java:119)
        at ij.macro.Interpreter.run(Interpreter.java:90)
        at ij.macro.Interpreter.run(Interpreter.java:101)
        at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
        at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:145)
        at ij.IJ.runMacroFile(IJ.java:159)
        at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:1115)
        at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:1111)
        at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1045)
        at net.imagej.legacy.IJ1Helper.runMacroFile(IJ1Helper.java:1111)
        at net.imagej.legacy.LegacyCommandline$Macro.handle(LegacyCommandline.java:187)
        at org.scijava.console.DefaultConsoleService.processArgs(DefaultConsoleService.java:102)
        at org.scijava.AbstractGateway.launch(AbstractGateway.java:97)
        at net.imagej.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.awt.HeadlessException
        at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:294)
        ... 34 more```

Running it without headless works fine, but that's not always as easily done in an production environment.

**Comment by harshamarupudi56** [comment]
Hello I am having a similar issue attempting to run BoneJ in headless mode. Were you able to find a solution?

**Comment by tjrantal** [comment]
I don't think I've never been able to run the plugin in the headless mode. Definitely not when I was trying to produce visualisation images. I suspect I used a method that required a display somewhere.
